

services:
  db:
    image: postgres:18.4
    container_name: postgresql
    environment:
      POSTGRES_DB: "ywgparcel"
      POSTGRES_USER: "ywgparceluser"
      POSTGRES_PASSWORD: "ywgparcelpass"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: always

  web:
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
        PYTHONDONTWRITEBYTECODE: 1
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --loop uvloop

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    devices:
      - /dev/dri:/dev/dri
    environment:
      - OLLAMA_REMOTES=!
      - OLLAMA_VULKAN=1
    mem_limit: 48g
    depends_on:
      - web
    restart: always
    entrypoint: [
      "/bin/bash", "-c", "\
      ollama serve & \
      sleep 6 && \
      ollama run gemma3:12b && \
      wait"
    ]

volumes:
  postgres_data:
  ollama:
